# ===========================================================================
# Project:   Test
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:'endash', "sproutcore/ace"], :css_theme => "ace"   
